version : '3'

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    healthcheck:
      test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/ccarnot
    env_file: .env
    restart: always
    healthcheck:
      test: netstat -an | grep 9000 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/ccarnot
    env_file: .env
    restart: always
    healthcheck:
      test: 'curl -kfsSL https://localhost:443/status'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

  redis:
    container_name: redis
    image: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "6379:6379"
    env_file: .env
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  vsftpd:
    build: ./requirements/bonus/ftp_server
    container_name: ftp
    image: ftp
    volumes:
      - wordpress:/var/www/ccarnot
    ports:
      - "0.0.0.0:21:21"
      - "0.0.0.0:20:20"
      - "0.0.0.0:30000-30009:30000-30009"
    env_file:
      - .env
    restart: unless-stopped
    init: true
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy

  static_site:
    build: ./requirements/bonus/static_site
    container_name: static_site
    image: static_site
    ports:
      - "81:81"
    restart: unless-stopped
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    ports:
      - "8080"
    restart: unless-stopped
    networks:
      - inception
    depends_on:
      - mariadb

  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    image: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - "9000:9000"
    restart: always
    init: true
    networks:
      - inception
    env_file: .env

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ccarnot/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ccarnot/data/wordpress'
  portainer:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ccarnot/data/portainer'

networks:
  inception:
    driver: bridge
    name: inception
